/* Even Fibonacci Numbers 
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values 
do not exceed four million, find the sum of the even-valued terms.

*/

var sum = 2;
var first = 1;
var second = 2;

while (second < 4000000) {
	currentNum = second + first
	if (currentNum % 2 === 0 && currentNum < 4000000) {
		sum += currentNum;
	} 
	first = second
	second = currentNum
}	
console.log(sum)
 
 /*var fibNum = function(num,value) {
 	this.num = num;
 	this.value = value;

 }

var first = new fibNum(1,1);
var second = new fibNum(1,2);
var sum = 0;

while (second.value < 4000000) {
	currentNum = second.value + first.value;
	if (second.num % 2 == 0) {
		sum += currentNum
	}
	first.value = second.value
	second.value = currentNum
}
console.log(sum)*/